                   TO_CHAR(id),                                                                             ID,                   
                   data_necessita,                                                                          DATA_NECESSITA,       
                   TO_CHAR(cod_cliente),                                                                    COD_CLIENTE,          
                   TO_CHAR(descri_cli),                                                                     DESCRI_CLI,           
                   TO_CHAR(num_ord),                                                                        NUM_ORD,              
                   id_big_cassa,                                                                            ID_BIG_CASSA,         
                   TO_CHAR(big_cassa),                                                                      BIG_CASSA,            
--                   SUM (casse_per_big_cassa) tot_casse_per_big_cassa,                                     
                   SUM (casse_per_big_cassa) casse_per_big_cassa,                                           CASSE_PER_BIG_CASSA,  
                   SUM (peso_big_cassa) peso_big_cassa,                                                     PESO_BIG_CASSA,       
                   TO_CHAR(MIN (um_peso)) um_peso_in_big,                                                   UM_PESO_IN_BIG,       
                   TO_CHAR(MIN (um_peso)) um_peso,                                                          UM_PESO,              
                   null netto_big_cassa,                                                                    NETTO_BIG_CASSA,      
                   MIN (um_peso) um_peso_netto,                                                             IDORD,                
                   idord,                                                                                   COD_SPEDIZIONIERE,    
                   cod_spedizioniere,                                                                       DESCRI_SPEDIZIONIERE, 
                   descri_spedizioniere,                                                                    STATO_ORD,            
                   stato_ord,                                                                               DIS_BIG_CASSA,        
                   dis_big_cassa,                                                                           TRANSPORT_BOOKING_ID, 
                   transport_booking_id,                                                                    DATA_BOOKING,         
                   data_booking,                                                                            DATA_EXPECTED_PICK_UP,
                   data_expected_pick_up,                                                                   DATA_PICK_UP,         
                   data_pick_up,                                                                            NOTE,                 
                   note,                           --MI002 - MI.WUP201603.MI02                              LUNGHEZZA_BIG_CASSA,  
                   lunghezza_big_cassa,                                                                     LARGHEZZA_BIG_CASSA,  
                   larghezza_big_cassa,                                                                     ALTEZZA_BIG_CASSA,    
                   altezza_big_cassa,                                                                       UM_LONGITUDINE,       
                   TO_CHAR(um_longitudine),                                                                 VOLUME_BIG_CASSA,     
                   volume_big_cassa,                                                                        UM_VOLUME,            
                   um_volume,                                                                               COD_PERC,             
                   cod_perc,                                                                                MARC1,                
                   marc1,                                                                                   MARC2,                
                   marc2,                                                                                   MARC3,                
                   marc3,                                                                                   MARC4,                
                   marc4,                                                                                   MARC5                 
                   marc5
                   
                   AAAAAAAAAAAAAAAAAAAAAAAAAA